// Export utilities for PDF, CSV, and Excel files
import * as XLSX from 'xlsx';

// CSV Export Function
export const exportToCSV = (data, filename, headers = null) => {
  if (!data || data.length === 0) {
    alert('No data to export');
    return;
  }

  // Generate headers from first object if not provided
  const csvHeaders = headers || Object.keys(data[0]);
  
  // Create CSV content
  const csvContent = [
    csvHeaders.join(','), // Header row
    ...data.map(row => 
      csvHeaders.map(header => {
        const value = row[header] || '';
        // Escape commas and quotes in values
        return typeof value === 'string' && (value.includes(',') || value.includes('"'))
          ? `"${value.replace(/"/g, '""')}"` 
          : value;
      }).join(',')
    )
  ].join('\n');

  // Create and download file
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

// Excel Export Function using XLSX library
export const exportToExcel = (data, filename, headers = null) => {
  if (!data || data.length === 0) {
    alert('No data to export');
    return;
  }

  // Create workbook and worksheet
  const wb = XLSX.utils.book_new();
  
  // Convert data to worksheet
  const ws = XLSX.utils.json_to_sheet(data);
  
  // Add worksheet to workbook
  XLSX.utils.book_append_sheet(wb, ws, 'Data');
  
  // Generate Excel file and trigger download
  XLSX.writeFile(wb, `${filename}.xlsx`);
};

// PDF Export Function (HTML to PDF)
export const exportToPDF = (data, filename, title, headers = null) => {
  if (!data || data.length === 0) {
    alert('No data to export');
    return;
  }

  const tableHeaders = headers || Object.keys(data[0]);
  
  // Create HTML content
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #37514D; text-align: center; margin-bottom: 10px; }
        .date { text-align: center; color: #666; margin-bottom: 30px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #37514D; color: white; font-weight: bold; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { margin-top: 30px; text-align: center; color: #666; font-size: 12px; }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <div class="date">Generated on: ${new Date().toLocaleDateString()}</div>
      <table>
        <thead>
          <tr>
            ${tableHeaders.map(header => `<th>${header}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${data.map(row => `
            <tr>
              ${tableHeaders.map(header => `<td>${row[header] || ''}</td>`).join('')}
            </tr>
          `).join('')}
        </tbody>
      </table>
      <div class="footer">
        <p>Total Records: ${data.length}</p>
        <p>Generated by bInvite Dashboard</p>
      </div>
    </body>
    </html>
  `;

  // Create a new window and print
  const printWindow = window.open('', '_blank');
  printWindow.document.write(htmlContent);
  printWindow.document.close();
  
  // Wait for content to load then print
  printWindow.onload = () => {
    printWindow.print();
    printWindow.close();
  };
};

// Templates Export Functions
export const exportTemplates = (templates, format = 'csv') => {
  const headers = ['ID', 'Name', 'Category', 'Price', 'Orders', 'Status', 'Rating', 'Created Date'];
  const exportData = templates.map(template => ({
    'ID': template.id,
    'Name': template.name || template.title,
    'Category': template.category,
    'Price': `₹${template.price || 0}`,
    'Orders': template.orders || 0,
    'Status': template.status || 'Active',
    'Rating': template.rating || 'N/A',
    'Created Date': template.created_at ? new Date(template.created_at).toLocaleDateString() : 'N/A'
  }));

  const filename = `templates_${new Date().toISOString().split('T')[0]}`;

  switch (format) {
    case 'pdf':
      exportToPDF(exportData, filename, 'Templates Report', headers);
      break;
    case 'excel':
      exportToExcel(exportData, filename, headers);
      break;
    default:
      exportToCSV(exportData, filename, headers);
  }
};

// Orders Export Functions
export const exportOrders = (orders, format = 'csv') => {
  const headers = ['Order ID', 'Customer', 'Email', 'Type', 'Status', 'Amount', 'Date', 'Phone'];
  const exportData = orders.map(order => ({
    'Order ID': order.id,
    'Customer': order.customer,
    'Email': order.email,
    'Type': order.type,
    'Status': order.status,
    'Amount': order.amount,
    'Date': order.date,
    'Phone': order.phone || 'N/A'
  }));

  const filename = `orders_${new Date().toISOString().split('T')[0]}`;

  switch (format) {
    case 'pdf':
      exportToPDF(exportData, filename, 'Orders Report', headers);
      break;
    case 'excel':
      exportToExcel(exportData, filename, headers);
      break;
    default:
      exportToCSV(exportData, filename, headers);
  }
};

// Customers Export Functions
export const exportCustomers = (customers, format = 'csv') => {
  const headers = ['ID', 'Name', 'Email', 'Phone', 'Segment', 'Orders', 'Total Spent', 'Status', 'Join Date'];
  const exportData = customers.map(customer => ({
    'ID': customer.id,
    'Name': customer.name,
    'Email': customer.email,
    'Phone': customer.phone || 'N/A',
    'Segment': customer.segment,
    'Orders': customer.orders || 0,
    'Total Spent': `$${customer.totalSpent || 0}`,
    'Status': customer.status,
    'Join Date': customer.joinDate || 'N/A'
  }));

  const filename = `customers_${new Date().toISOString().split('T')[0]}`;

  switch (format) {
    case 'pdf':
      exportToPDF(exportData, filename, 'Customers Report', headers);
      break;
    case 'excel':
      exportToExcel(exportData, filename, headers);
      break;
    default:
      exportToCSV(exportData, filename, headers);
  }
};

// Analytics Export Functions
export const exportAnalytics = (dashboardData, format = 'csv') => {
  const analyticsData = [
    {
      'Metric': 'Total Templates',
      'Value': dashboardData?.templates?.length || 0,
      'Description': 'Total number of invitation templates'
    },
    {
      'Metric': 'Total Invitations',
      'Value': dashboardData?.totalInvitations || 0,
      'Description': 'Total invitations created'
    },
    {
      'Metric': 'Total Orders',
      'Value': dashboardData?.totalOrders || 0,
      'Description': 'Total orders placed'
    },
    {
      'Metric': 'Total Revenue',
      'Value': `$${dashboardData?.totalRevenue?.toLocaleString() || 0}`,
      'Description': 'Total revenue generated'
    }
  ];

  const headers = ['Metric', 'Value', 'Description'];
  const filename = `analytics_${new Date().toISOString().split('T')[0]}`;

  switch (format) {
    case 'pdf':
      exportToPDF(analyticsData, filename, 'Analytics Report', headers);
      break;
    case 'excel':
      exportToExcel(analyticsData, filename, headers);
      break;
    default:
      exportToCSV(analyticsData, filename, headers);
  }
};